camunda.bpm:
  webapp:
    index-redirect-enabled: true
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
#spring:
#  datasource:
#    url: jdbc:h2:./test;DB_CLOSE_ON_EXIT=FALSE
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camunda?characterEncoding=UTF-8&nullCatalogMeansCurrent=true&serverTimezone=GMT&useSSL=false
    username: root
    password: 123456
# camunda config

camunda:
  bpm:
    history-level: audit
logging:
  level:
    org.springframework: INFO
    camunda.bpm: INFO
    cn.sf80.lib.study.camunda: DEBUG